version: '4.3' 

services:
  # Service untuk aplikasi web Python kita (backend)
  web:
    build:
      context: . 
      dockerfile: Dockerfile 
    ports:
      - "8000:5000" 
    volumes:
      - .:/app 
               
    env_file:
      - .env 
    depends_on:
      - db 

  # Service untuk database MySQL
  db:
    image: mysql:8.0
    ports:
      - "3307:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: supersecretrootpassword # Kata sandi root MySQL. Ga ada isinya
      MYSQL_DATABASE: ${DATABASE_NAME}             # Ambil dari .env
      MYSQL_USER: ${DATABASE_USER}                 # sama jua
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}         
    volumes:
      - db_data:/var/lib/mysql 

volumes:
  db_data: # Ini adalah named volume. Data MySQL nya disimpan di sini di host,
           # supaya tidak hilang saat container 'db' di-stop/dihapus.