version: '3.8'

services:
  # Service untuk aplikasi web Python kita (backend)
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

  # Service untuk database MySQL
  db:
    image: mysql:8.0
    ports:
      - "3307:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: supersecretrootpassword
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  # Service untuk phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8081:80" 
    environment:
      PMA_HOST: db 
      MYSQL_ROOT_PASSWORD: supersecretrootpassword 
    depends_on:
      - db 

volumes:
  db_data: