name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Workflow akan berjalan setiap kali ada push ke branch 'main'

jobs:
  build:
    runs-on: ubuntu-latest # Jalankan job ini di lingkungan Ubuntu terbaru

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Mengambil kode dari repositori Anda

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Mengambil username dari GitHub Secrets
          password: ${{ secrets.DOCKER_TOKEN }}    # Mengambil token dari GitHub Secrets

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: . # Direktori konteks build Docker
          file: ./Dockerfile # Lokasi Dockerfile Anda
          push: true # Dorong image ke Docker Hub
          tags: ${{ secrets.DOCKER_USERNAME }}/petshop-app:latest # Tag image Anda. Ganti DOCKER_USERNAME!