name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Workflow akan berjalan setiap kali ada push ke branch 'main' - updated comment

jobs:
  build:
    runs-on: ubuntu-latest # Jalankan job ini di lingkungan Ubuntu terbaru

    steps: #wililili
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/petshop-app:latest